version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27018:27017
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-nest
    ports:
      - 5672:5672
      - 15672:15672    
  capture_info_app:
    build:
      context: ./capture_info_app
      dockerfile: Dockerfile
    container_name: capture_info_app
    ports:
      - 3000:3000
  set_info_app:
    build:
      context: ./set_info_app
      dockerfile: Dockerfile
    container_name: set_info_app
    ports:
      - 3001:3000
